<div class="container" style="margin-top:50px">
	<div class="row">
		<div class="span4 offset2">
			<div class="alert alert-error">
  				<h3>密码错误</h3>
  				<p>你输入的密码不对</p>
			</div>
			<br>
			<a href="<?php echo $_SERVER['REQUEST_URI']; ?>" class="btn btn-danger btn-large">返回重新输入密码</a>
			<br>
			<hr>
			<br>
			<a href="/user/register" class="btn btn-info btn-large">注册</a>
			<a href="/" class="btn btn-success btn-large">返回首页</a>
		</div>
		<div class="span5">
			<img src="/css/sc/404.jpg">
		</div>
	</div>
</div>
