
</div><div id="footer">
      <div class="container">
        <p class="muted credit">&copy;Copyright 2012-<?php echo date("Y"); ?> <a href="http://www.shashi-inc.com" target="_blank">Shanghai Shashi Network Technology Co.,Ltd</a>. All rights reserved.<span  class="pull-right" style="cursor:pointer" onclick="javascript:window.open('http://www.miitbeian.gov.cn');">沪ICP备13002754号</span></p>

      </div>
</div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    
    <script src="/assets/js/bootstrap-transition.js"></script>
    <script src="/assets/js/bootstrap-alert.js"></script>
    <script src="/assets/js/bootstrap-modal.js"></script>
    <script src="/assets/js/bootstrap-dropdown.js"></script>
    <script src="/assets/js/bootstrap-scrollspy.js"></script>
    <script src="/assets/js/bootstrap-tab.js"></script>
    <script src="/assets/js/bootstrap-tooltip.js"></script>
    <script src="/assets/js/bootstrap-popover.js"></script>
    <script src="/assets/js/bootstrap-button.js"></script>
    <script src="/assets/js/bootstrap-collapse.js"></script>
    <script src="/assets/js/bootstrap-carousel.js"></script>
    <script src="/assets/js/bootstrap-typeahead.js"></script>
    <script type="text/javascript">
    $(document).ready(function(){
        $("#<?php echo $activetab; ?>").attr("class","active");

    });
    </script>
  </body>
</html>
