  <body>
<div id="wrap">
  <div id="loadingbar"></div>
    <div class="navbar navbar-reverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">HM</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li id="indexpage"><a href="/">首页</a></li>
              <li id="github"><a href="<?php 
              if (isset($_SESSION['is_login'])) {
                echo "https://github.com/yinzhiping/HyperMobile-ios";
              }else{
                echo "javascript:alert('登陆后该链接才能跳转')";
              }
              ?>" target="_blank">github</a></li>
              <?php
              if (isset($_SESSION['is_login'])) {
                echo '<li><a href="/project/lists">项目列表</a></li>';
                echo '<li><a href="/project/template">模板浏览</a></li>';
              }
            
              ?>
            </ul>
            <ul class="nav pull-right">
                <?php 
                  if ($_SESSION['is_login']==1) {
                    echo '<li><a href="/project/index">欢迎:'.$_SESSION['username'].'</a></li><li class="divider-vertical"></li><li><a href="/user/logout">退出</a></li>';
                  } else {
                    echo '<li><a href="/user/login">登录</a></li>';
                  }
                  

                ?>
            </ul>
            

            
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
